name: docs
on:
  push:
    branches:
      - main

env:
  deploy-dir: .gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Create docs
        uses: actions/checkout@v3
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
        run: |
          nimble install -Y
          find src -maxdepth 2 -name '*.nim' -exec nim doc --outdir:${{ env.deploy-dir }} --path:./src --index:on --git.url:https://github.com/jnb666/nimxla --git.commit:main {} \\;
          nim buildIndex -o:${{ env.deploy-dir }}/theindex.html ${{ env.deploy-dir }}
          cp ${{ env.deploy-dir }}/theindex.html ${{ env.deploy-dir }}/index.html

      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}